services:
  - type: web
    name: eali-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn backend_core.wsgi
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eali-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: eali-db
    databaseName: eali_db
    user: eali_user
